export const actionTypes = {
  FETCHING_REQUEST: "FETCHING_REQUEST",
  FETCH_DRINKS_SUCCESS: "FETCH_DRINKS_SUCCESS",
  FETCH_DRINK_DETAIL_SUCCESS: "FETCH_DRINK_DETAIL_SUCCESS",
  SET_FILTER: "SET_FILTER",
  RAISE_ERROR: "RAISE_ERROR"
};
