export const CHANGE_APP_STATE = 'CHANGE_APP_STATE'
export const GET_COCKTAILS = 'GET_COCKTAILS'
export const GET_COCKTAIL_DETAILS = 'GET_COCKTAIL_DETAILS'
export const FILTER_COCKTAILS = 'FILTER_COCKTAILS'