export const GET_DRINKS = 'GET_DRINKS'
export const GET_DRINKS_SUCCESS = 'GET_DRINKS_SUCCESS'
export const GET_DRINKS_FAILURE = 'GET_DRINKS_FAILURE'

export const GET_DRINKS_DETAILS = 'GET_DRINKS_DETAILS'
export const GET_DRINKS_DETAILS_SUCCESS = 'GET_DRINKS_DETAILS_SUCCESS'
export const GET_DRINKS_DETAILS_FAILURE = 'GET_DRINKS_DETAILS_FAILURE'
