const cocktailActions = {
  COCKTAIL_LIST_REQUEST: 'COCKTAIL_LIST_REQUEST',
  COCKTAIL_LIST_SUCCESS: 'COCKTAIL_LIST_SUCCESS',
  COCKTAIL_LIST_ERROR: 'COCKTAIL_LIST_ERROR',
  getList: () => ({
    type: cocktailActions.COCKTAIL_LIST_REQUEST
  }),
  COCKTAIL_DETAILS_REQUEST: 'COCKTAIL_DETAILS_REQUEST',
  COCKTAIL_DETAILS_SUCCESS: 'COCKTAIL_DETAILS_SUCCESS',
  COCKTAIL_DETAILS_ERROR: 'COCKTAIL_DETAILS_ERROR',
  getDetails: payload => ({
    type: cocktailActions.COCKTAIL_DETAILS_REQUEST,
    payload
  })
};

export default cocktailActions;