export const FETCH_LIST = "FETCH_LIST";
export const FETCH_LIST_SUCCESS = "FETCH_LIST_SUCCESS";
export const FETCH_LIST_ERROR = "FETCH_LIST_SUCCESS";

export const FETCH_DETAIL = "FETCH_DETAIL";
export const FETCH_DETAIL_SUCCESS = "FETCH_DETAIL_SUCCESS";
export const FETCH_DETAIL_ERROR = "FETCH_DETAIL_ERROR";
export const CLEAN_DETAIL = "CLEAN_DETAIL";

export const SELECT_DRINK = "SELECT_DRINK";
export const SHOULD_FETCH_DETAIL = "SHOULD_FETCH_DETAIL";

export const RAISE_ERROR = 'RAISE_ERROR';