# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FECODETEST' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FECODETEST

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

end

