platform :ios, '10.0'

target 'Drinks' do
  use_frameworks!
  
  #pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
  
  pod 'PinLayout'
  pod 'Alamofire'
  pod "PromiseKit", "~> 6.0"
  pod 'RealmSwift'
  pod "EasyRealm", '~> 2.0.0'
  pod 'Swinject'
  pod 'ReachabilitySwift'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'CodableAlamofire'
  pod 'Kingfisher'
  pod 'Dip'
  pod 'Dip-UI'
end
