export const NAME = 'cocktails';

export const FETCH_COCKTAILS = `${NAME}/FETCH_COCKTAILS`;
export const FETCH_COCKTAILS_SUCCESS = `${NAME}/FETCH_COCKTAILS_SUCCESS`;
export const FETCH_COCKTAILS_FAILURE = `${NAME}/FETCH_COCKTAILS_FAILURE`;

export const FETCH_COCKTAIL = `${NAME}/FETCH_COCKTAIL`;
export const FETCH_COCKTAIL_SUCCESS = `${NAME}/FETCH_COCKTAIL_SUCCESS`;
export const FETCH_COCKTAIL_FAILURE = `${NAME}/FETCH_COCKTAIL_FAILURE`;
