export const LOAD_COCKTAIL_LIST = 'App/LOAD_COCKTAIL_LIST';
export const LOAD_COCKTAIL_LIST_SUCCESS = 'App/LOAD_COCKTAIL_LIST_SUCCESS';
export const LOAD_COCKTAIL_LIST_ERROR = 'App/LOAD_COCKTAIL_LIST_ERROR';
