export const LOAD_COCKTAIL_DETAIL = 'App/LOAD_COCKTAIL_DETAIL';
export const LOAD_COCKTAIL_DETAIL_SUCCESS = 'App/LOAD_COCKTAIL_DETAIL_SUCCESS';
export const LOAD_COCKTAIL_DETAIL_ERROR = 'App/LOAD_COCKTAIL_DETAIL_ERROR';
